#!/bin/sh

if [[ $# -ne 1 ]]; then
    echo "Usage: signal-process-end PROCESS_NAME"
    exit 1
fi

while true; do

    sleep 1

    # If pgrep call is empty, then the program is no longer running and so is probably finished with its task
    if [[ -z $(pgrep "$1") ]]; then
        mplayer ~/bin/assets/alrm.opus
    fi

done
